import type { YearlyData, ServiceData } from "./DataType";
import type { ContractsData } from "./DataType";

export const dataAnalytic: YearlyData = {
    year: "2025",

    months: [
        {
            month: "01/2025",
            totalTransactions: 145,
            successfulTransactions: 118,
            cancelledTransactions: 17,
            unpaidTransactions: 10,
            onlineTransactions: 92,
            offlineTransactions: 53,
            totalRevenue: 52000000,
            totalUnpaindRevenue: 4200000,
        },

        {
            month: "02/2025",
            totalTransactions: 162,
            successfulTransactions: 136,
            cancelledTransactions: 14,
            unpaidTransactions: 12,
            onlineTransactions: 105,
            offlineTransactions: 57,
            totalRevenue: 61000000,
            totalUnpaindRevenue: 5100000,
        },

        {
            month: "03/2025",
            totalTransactions: 178,
            successfulTransactions: 149,
            cancelledTransactions: 18,
            unpaidTransactions: 11,
            onlineTransactions: 120,
            offlineTransactions: 58,
            totalRevenue: 72000000,
            totalUnpaindRevenue: 4800000,
        },

        {
            month: "04/2025",
            totalTransactions: 154,
            successfulTransactions: 128,
            cancelledTransactions: 16,
            unpaidTransactions: 10,
            onlineTransactions: 101,
            offlineTransactions: 53,
            totalRevenue: 64000000,
            totalUnpaindRevenue: 4600000,
        },

        {
            month: "05/2025",
            totalTransactions: 190,
            successfulTransactions: 161,
            cancelledTransactions: 19,
            unpaidTransactions: 10,
            onlineTransactions: 135,
            offlineTransactions: 55,
            totalRevenue: 81000000,
            totalUnpaindRevenue: 6200000,
        },

        {
            month: "06/2025",
            totalTransactions: 210,
            successfulTransactions: 180,
            cancelledTransactions: 20,
            unpaidTransactions: 10,
            onlineTransactions: 152,
            offlineTransactions: 58,
            totalRevenue: 93000000,
            totalUnpaindRevenue: 7500000,
        },

        {
            month: "07/2025",
            totalTransactions: 198,
            successfulTransactions: 168,
            cancelledTransactions: 18,
            unpaidTransactions: 12,
            onlineTransactions: 146,
            offlineTransactions: 52,
            totalRevenue: 89000000,
            totalUnpaindRevenue: 7100000,
        },

        {
            month: "08/2025",
            totalTransactions: 225,
            successfulTransactions: 194,
            cancelledTransactions: 19,
            unpaidTransactions: 12,
            onlineTransactions: 171,
            offlineTransactions: 54,
            totalRevenue: 105000000,
            totalUnpaindRevenue: 8400000,
        },

        {
            month: "09/2025",
            totalTransactions: 214,
            successfulTransactions: 183,
            cancelledTransactions: 20,
            unpaidTransactions: 11,
            onlineTransactions: 158,
            offlineTransactions: 56,
            totalRevenue: 98000000,
            totalUnpaindRevenue: 7900000,
        },

        {
            month: "10/2025",
            totalTransactions: 238,
            successfulTransactions: 205,
            cancelledTransactions: 21,
            unpaidTransactions: 12,
            onlineTransactions: 182,
            offlineTransactions: 56,
            totalRevenue: 118000000,
            totalUnpaindRevenue: 9300000,
        },

        {
            month: "11/2025",
            totalTransactions: 252,
            successfulTransactions: 220,
            cancelledTransactions: 20,
            unpaidTransactions: 12,
            onlineTransactions: 194,
            offlineTransactions: 58,
            totalRevenue: 126000000,
            totalUnpaindRevenue: 10100000,
        },

        {
            month: "12/2025",
            totalTransactions: 310,
            successfulTransactions: 276,
            cancelledTransactions: 22,
            unpaidTransactions: 12,
            onlineTransactions: 250,
            offlineTransactions: 60,
            totalRevenue: 168000000,
            totalUnpaindRevenue: 12800000,
        },
    ],
};

export const services: Record<string, ServiceData[]> = {

    "01/2025": [

        {
            month: "01/2025",
            serviceName: "Khám bệnh Bác sĩ",
            price: 100000,
            patientCount: 52,
            totalTransactions: 58,
            successfulTransactions: 45,
            cancelledTransactions: 6,
            unpaidTransactions: 7,
            onlineTransactions: 40,
            offlineTransactions: 18,
            totalRevenue: 5800000,
        },

        {
            month: "01/2025",
            serviceName: "Khám bệnh Bác sĩ chuyên khoa",
            price: 150000,
            patientCount: 41,
            totalTransactions: 45,
            successfulTransactions: 36,
            cancelledTransactions: 4,
            unpaidTransactions: 5,
            onlineTransactions: 33,
            offlineTransactions: 12,
            totalRevenue: 6750000,
        },

        {
            month: "01/2025",
            serviceName: "Khám bệnh Thạc sĩ",
            price: 150000,
            patientCount: 38,
            totalTransactions: 42,
            successfulTransactions: 34,
            cancelledTransactions: 3,
            unpaidTransactions: 5,
            onlineTransactions: 30,
            offlineTransactions: 12,
            totalRevenue: 6300000,
        },

        {
            month: "01/2025",
            serviceName: "Khám bệnh Tiến sĩ",
            price: 200000,
            patientCount: 28,
            totalTransactions: 32,
            successfulTransactions: 25,
            cancelledTransactions: 3,
            unpaidTransactions: 4,
            onlineTransactions: 24,
            offlineTransactions: 8,
            totalRevenue: 6400000,
        },

        {
            month: "01/2025",
            serviceName: "Khám bệnh Bác sĩ (ngoài giờ)",
            price: 100000,
            patientCount: 33,
            totalTransactions: 36,
            successfulTransactions: 28,
            cancelledTransactions: 3,
            unpaidTransactions: 5,
            onlineTransactions: 24,
            offlineTransactions: 12,
            totalRevenue: 3600000,
        },

        {
            month: "01/2025",
            serviceName: "Khám bệnh Bác sĩ chuyên khoa (ngoài giờ)",
            price: 200000,
            patientCount: 24,
            totalTransactions: 27,
            successfulTransactions: 21,
            cancelledTransactions: 2,
            unpaidTransactions: 4,
            onlineTransactions: 20,
            offlineTransactions: 7,
            totalRevenue: 5400000,
        },

        {
            month: "01/2025",
            serviceName: "Khám bệnh Thạc sĩ (ngoài giờ)",
            price: 200000,
            patientCount: 22,
            totalTransactions: 25,
            successfulTransactions: 19,
            cancelledTransactions: 2,
            unpaidTransactions: 4,
            onlineTransactions: 18,
            offlineTransactions: 7,
            totalRevenue: 5000000,
        },

        {
            month: "01/2025",
            serviceName: "Khám tư vấn dinh dưỡng",
            price: 150000,
            patientCount: 18,
            totalTransactions: 20,
            successfulTransactions: 16,
            cancelledTransactions: 2,
            unpaidTransactions: 2,
            onlineTransactions: 14,
            offlineTransactions: 6,
            totalRevenue: 3000000,
        },

        {
            month: "01/2025",
            serviceName: "Khám tư vấn dinh dưỡng (ngoài giờ)",
            price: 200000,
            patientCount: 12,
            totalTransactions: 14,
            successfulTransactions: 11,
            cancelledTransactions: 1,
            unpaidTransactions: 2,
            onlineTransactions: 11,
            offlineTransactions: 3,
            totalRevenue: 2800000,
        },

        {
            month: "01/2025",
            serviceName: "Khám bác sỹ chuyên khoa II",
            price: 200000,
            patientCount: 16,
            totalTransactions: 18,
            successfulTransactions: 14,
            cancelledTransactions: 2,
            unpaidTransactions: 2,
            onlineTransactions: 13,
            offlineTransactions: 5,
            totalRevenue: 3600000,
        },
    ],

    "02/2025": [

        {
            month: "02/2025",
            serviceName: "Khám bệnh Bác sĩ",
            price: 100000,
            patientCount: 60,
            totalTransactions: 66,
            successfulTransactions: 53,
            cancelledTransactions: 5,
            unpaidTransactions: 8,
            onlineTransactions: 47,
            offlineTransactions: 19,
            totalRevenue: 6600000,
        },

        {
            month: "02/2025",
            serviceName: "Khám bệnh Bác sĩ chuyên khoa",
            price: 150000,
            patientCount: 48,
            totalTransactions: 53,
            successfulTransactions: 42,
            cancelledTransactions: 4,
            unpaidTransactions: 7,
            onlineTransactions: 38,
            offlineTransactions: 15,
            totalRevenue: 7950000,
        },

        {
            month: "02/2025",
            serviceName: "Khám bệnh Thạc sĩ",
            price: 150000,
            patientCount: 44,
            totalTransactions: 49,
            successfulTransactions: 39,
            cancelledTransactions: 4,
            unpaidTransactions: 6,
            onlineTransactions: 35,
            offlineTransactions: 14,
            totalRevenue: 7350000,
        },

        {
            month: "02/2025",
            serviceName: "Khám bệnh Tiến sĩ",
            price: 200000,
            patientCount: 34,
            totalTransactions: 38,
            successfulTransactions: 30,
            cancelledTransactions: 3,
            unpaidTransactions: 5,
            onlineTransactions: 29,
            offlineTransactions: 9,
            totalRevenue: 7600000,
        },

        {
            month: "02/2025",
            serviceName: "Khám bệnh Bác sĩ (ngoài giờ)",
            price: 100000,
            patientCount: 40,
            totalTransactions: 44,
            successfulTransactions: 35,
            cancelledTransactions: 3,
            unpaidTransactions: 6,
            onlineTransactions: 31,
            offlineTransactions: 13,
            totalRevenue: 4400000,
        },

        {
            month: "02/2025",
            serviceName: "Khám bệnh Bác sĩ chuyên khoa (ngoài giờ)",
            price: 200000,
            patientCount: 28,
            totalTransactions: 31,
            successfulTransactions: 24,
            cancelledTransactions: 3,
            unpaidTransactions: 4,
            onlineTransactions: 23,
            offlineTransactions: 8,
            totalRevenue: 6200000,
        },

        {
            month: "02/2025",
            serviceName: "Khám bệnh Thạc sĩ (ngoài giờ)",
            price: 200000,
            patientCount: 25,
            totalTransactions: 28,
            successfulTransactions: 22,
            cancelledTransactions: 2,
            unpaidTransactions: 4,
            onlineTransactions: 21,
            offlineTransactions: 7,
            totalRevenue: 5600000,
        },

        {
            month: "02/2025",
            serviceName: "Khám tư vấn dinh dưỡng",
            price: 150000,
            patientCount: 22,
            totalTransactions: 24,
            successfulTransactions: 19,
            cancelledTransactions: 2,
            unpaidTransactions: 3,
            onlineTransactions: 17,
            offlineTransactions: 7,
            totalRevenue: 3600000,
        },

        {
            month: "02/2025",
            serviceName: "Khám tư vấn dinh dưỡng (ngoài giờ)",
            price: 200000,
            patientCount: 16,
            totalTransactions: 18,
            successfulTransactions: 14,
            cancelledTransactions: 1,
            unpaidTransactions: 3,
            onlineTransactions: 14,
            offlineTransactions: 4,
            totalRevenue: 3600000,
        },

        {
            month: "02/2025",
            serviceName: "Khám bác sỹ chuyên khoa II",
            price: 200000,
            patientCount: 20,
            totalTransactions: 22,
            successfulTransactions: 17,
            cancelledTransactions: 2,
            unpaidTransactions: 3,
            onlineTransactions: 16,
            offlineTransactions: 6,
            totalRevenue: 4400000,
        },
    ],
};

export const contracts: ContractsData = [
    {
        title: "Hợp đồng 1",
        money: 1000000,
        type: "receive",
        date: "2026-05-01",
        note: "Ghi chú hợp đồng 1"
    },
    {
        title: "Hợp đồng 2",
        money: 2000000,
        type: "receive",
        date: "2026-05-02",
        note: "Ghi chú hợp đồng 2"
    },
    {
        title: "Hợp đồng 3",
        money: 1500000,
        type: "pay",
        date: "2026-05-05",
        note: "Ghi chú hợp đồng 3"
    },
    {
        title: "Hợp đồng 4",
        money: 2000000,
        type: "receive",
        date: "2026-05-15",
        note: "Ghi chú hợp đồng 4"
    },
    {
        title: "Hợp đồng 5",
        money: 1000000,
        type: "receive",
        date: "2026-06-02",
        note: "Ghi chú hợp đồng 5"
    },
    {
        title: "Hợp đồng 6",
        money: 2000000,
        type: "pay",
        date: "2026-06-02",
        note: "Ghi chú hợp đồng 6"
    },
    {
        title: "Hợp đồng 7",
        money: 1500000,
        type: "receive",
        date: "2026-06-02",
        note: "Ghi chú hợp đồng 7"
    },
    {
        title: "Hợp đồng 8",
        money: 1000000,
        type: "receive",
        date: "2026-07-02",
        note: "Ghi chú hợp đồng 8"
    },
    {
        title: "Hợp đồng 9",
        money: 2000000,
        type: "pay",
        date: "2026-07-05",
        note: "Ghi chú hợp đồng 9"
    },
    {
        title: "Hợp đồng 10",
        money: 2000000,
        type: "receive",
        date: "2026-08-02",
        note: "Ghi chú hợp đồng 10"
    },
    {
        title: "Hợp đồng 11",
        money: 1500000,
        type: "receive",
        date: "2026-08-11",
        note: "Ghi chú hợp đồng 11"
    },
];
